# Arreglos

In [2]:
import pandas as pd
import numpy as np

In [4]:
sample_array= np.array([1,2,3,4])
sample_array

array([1, 2, 3, 4])

In [5]:
sample_array.dtype

dtype('int64')

In [13]:
zeros = np.zeros((2,3), dtype= int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
zeros.dtype

dtype('int64')

In [17]:
random_array= np.random.randint(1,10, size=(4,2))
random_array

array([[5, 3],
       [2, 2],
       [5, 1],
       [7, 5]], dtype=int32)

In [18]:
random_array.size

8

# Random seeding

In [33]:
np.random.seed(2)
random_array2= np.random.random( size=(5,3))
random_array2

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467],
       [0.26682728, 0.62113383, 0.52914209],
       [0.13457995, 0.51357812, 0.18443987]])

In [37]:
random_array3 = np.random.randint(12, size=(7,4))

### 3. Mirando arreglos y matrices

In [38]:
np.unique(random_array3)

array([ 0,  1,  2,  3,  4,  5,  6,  8,  9, 10, 11], dtype=int32)

### 4. Manipulando y comparando arreglos